import NS from './NS.js';
import {TAG_ID} from './TAG/i.js';

export default {
    [NS.HTML]: new Set([
        TAG_ID.ADDRESS,
        TAG_ID.APPLET,
        TAG_ID.AREA,
        TAG_ID.ARTICLE,
        TAG_ID.ASIDE,
        TAG_ID.BASE,
        TAG_ID.BASEFONT,
        TAG_ID.BGSOUND,
        TAG_ID.BLOCKQUOTE,
        TAG_ID.BODY,
        TAG_ID.BR,
        TAG_ID.BUTTON,
        TAG_ID.CAPTION,
        TAG_ID.CENTER,
        TAG_ID.COL,
        TAG_ID.COLGROUP,
        TAG_ID.DD,
        TAG_ID.DETAILS,
        TAG_ID.DIR,
        TAG_ID.DIV,
        TAG_ID.DL,
        TAG_ID.DT,
        TAG_ID.EMBED,
        TAG_ID.FIELDSET,
        TAG_ID.FIGCAPTION,
        TAG_ID.FIGURE,
        TAG_ID.FOOTER,
        TAG_ID.FORM,
        TAG_ID.FRAME,
        TAG_ID.FRAMESET,
        TAG_ID.H1,
        TAG_ID.H2,
        TAG_ID.H3,
        TAG_ID.H4,
        TAG_ID.H5,
        TAG_ID.H6,
        TAG_ID.HEAD,
        TAG_ID.HEADER,
        TAG_ID.HGROUP,
        TAG_ID.HR,
        TAG_ID.HTML,
        TAG_ID.IFRAME,
        TAG_ID.IMG,
        TAG_ID.INPUT,
        TAG_ID.LI,
        TAG_ID.LINK,
        TAG_ID.LISTING,
        TAG_ID.MAIN,
        TAG_ID.MARQUEE,
        TAG_ID.MENU,
        TAG_ID.META,
        TAG_ID.NAV,
        TAG_ID.NOEMBED,
        TAG_ID.NOFRAMES,
        TAG_ID.NOSCRIPT,
        TAG_ID.OBJECT,
        TAG_ID.OL,
        TAG_ID.P,
        TAG_ID.PARAM,
        TAG_ID.PLAINTEXT,
        TAG_ID.PRE,
        TAG_ID.SCRIPT,
        TAG_ID.SECTION,
        TAG_ID.SELECT,
        TAG_ID.SOURCE,
        TAG_ID.STYLE,
        TAG_ID.SUMMARY,
        TAG_ID.TABLE,
        TAG_ID.TBODY,
        TAG_ID.TD,
        TAG_ID.TEMPLATE,
        TAG_ID.TEXTAREA,
        TAG_ID.TFOOT,
        TAG_ID.TH,
        TAG_ID.THEAD,
        TAG_ID.TITLE,
        TAG_ID.TR,
        TAG_ID.TRACK,
        TAG_ID.UL,
        TAG_ID.WBR,
        TAG_ID.XMP,
    ]),
    [NS.MATHML]: new Set([
        TAG_ID.MI,
        TAG_ID.MO,
        TAG_ID.MN,
        TAG_ID.MS,
        TAG_ID.MTEXT,
        TAG_ID.ANNOTATION_XML
    ]),
    [NS.SVG]: new Set([
        TAG_ID.TITLE,
        TAG_ID.FOREIGN_OBJECT,
        TAG_ID.DESC
    ]),
    [NS.XLINK]: new Set(),
    [NS.XML]: new Set(),
    [NS.XMLNS]: new Set(),
};
