

export default (
    {
        0: "INITIAL",
        1: "BEFORE_HTML",
        2: "BEFORE_HEAD",
        3: "IN_HEAD",
        4: "IN_HEAD_NO_SCRIPT",
        5: "AFTER_HEAD",
        6: "IN_BODY",
        7: "TEXT",
        8: "IN_TABLE",
        9: "IN_TABLE_TEXT",
        10: "IN_CAPTION",
        11: "IN_COLUMN_GROUP",
        12: "IN_TABLE_BODY",
        13: "IN_ROW",
        14: "IN_CELL",
        15: "IN_SELECT",
        16: "IN_SELECT_IN_TABLE",
        17: "IN_TEMPLATE",
        18: "AFTER_BODY",
        19: "IN_FRAMESET",
        20: "AFTER_FRAMESET",
        21: "AFTER_AFTER_BODY",
        22: "AFTER_AFTER_FRAMESET",
        
        INITIAL: 0,
        BEFORE_HTML: 1,
        BEFORE_HEAD: 2,
        IN_HEAD: 3,
        IN_HEAD_NO_SCRIPT: 4,
        AFTER_HEAD: 5,
        IN_BODY: 6,
        TEXT: 7,
        IN_TABLE: 8,
        IN_TABLE_TEXT: 9,
        IN_CAPTION: 10,
        IN_COLUMN_GROUP: 11,
        IN_TABLE_BODY: 12,
        IN_ROW: 13,
        IN_CELL: 14,
        IN_SELECT: 15,
        IN_SELECT_IN_TABLE: 16,
        IN_TEMPLATE: 17,
        AFTER_BODY: 18,
        IN_FRAMESET: 19,
        AFTER_FRAMESET: 20,
        AFTER_AFTER_BODY: 21,
        AFTER_AFTER_FRAMESET: 22
    }
);
