export var
    NS = {
        HTML: "http://www.w3.org/1999/xhtml",
        MATHML: "http://www.w3.org/1998/Math/MathML",
        SVG: "http://www.w3.org/2000/svg",
        XLINK: "http://www.w3.org/1999/xlink",
        XML: "http://www.w3.org/XML/1998/namespace",
        XMLNS: "http://www.w3.org/2000/xmlns/",
    },

    ATTRS = {
        TYPE: "type",
        ACTION: "action",
        ENCODING: "encoding",
        PROMPT: "prompt",
        NAME: "name",
        COLOR: "color",
        FACE: "face",
        SIZE: "size",
    },
    
    DOCUMENT_MODE = {
        NO_QUIRKS: "no-quirks",
        QUIRKS: "quirks",
        LIMITED_QUIRKS: "limited-quirks",
    },

    TAG_NAMES = {
        A: "a",
        ADDRESS: "address",
        ANNOTATION_XML: "annotation-xml",
        APPLET: "applet",
        AREA: "area",
        ARTICLE: "article",
        ASIDE: "aside",
        B: "b",
        BASE: "base",
        BASEFONT: "basefont",
        BGSOUND: "bgsound",
        BIG: "big",
        BLOCKQUOTE: "blockquote",
        BODY: "body",
        BR: "br",
        BUTTON: "button",
        CAPTION: "caption",
        CENTER: "center",
        CODE: "code",
        COL: "col",
        COLGROUP: "colgroup",
        DD: "dd",
        DESC: "desc",
        DETAILS: "details",
        DIALOG: "dialog",
        DIR: "dir",
        DIV: "div",
        DL: "dl",
        DT: "dt",
        EM: "em",
        EMBED: "embed",
        FIELDSET: "fieldset",
        FIGCAPTION: "figcaption",
        FIGURE: "figure",
        FONT: "font",
        FOOTER: "footer",
        FOREIGN_OBJECT: "foreignObject",
        FORM: "form",
        FRAME: "frame",
        FRAMESET: "frameset",
        H1: "h1",
        H2: "h2",
        H3: "h3",
        H4: "h4",
        H5: "h5",
        H6: "h6",
        HEAD: "head",
        HEADER: "header",
        HGROUP: "hgroup",
        HR: "hr",
        HTML: "html",
        I: "i",
        IMG: "img",
        IMAGE: "image",
        INPUT: "input",
        IFRAME: "iframe",
        KEYGEN: "keygen",
        LABEL: "label",
        LI: "li",
        LINK: "link",
        LISTING: "listing",
        MAIN: "main",
        MALIGNMARK: "malignmark",
        MARQUEE: "marquee",
        MATH: "math",
        MENU: "menu",
        META: "meta",
        MGLYPH: "mglyph",
        MI: "mi",
        MO: "mo",
        MN: "mn",
        MS: "ms",
        MTEXT: "mtext",
        NAV: "nav",
        NOBR: "nobr",
        NOFRAMES: "noframes",
        NOEMBED: "noembed",
        NOSCRIPT: "noscript",
        OBJECT: "object",
        OL: "ol",
        OPTGROUP: "optgroup",
        OPTION: "option",
        P: "p",
        PARAM: "param",
        PLAINTEXT: "plaintext",
        PRE: "pre",
        RB: "rb",
        RP: "rp",
        RT: "rt",
        RTC: "rtc",
        RUBY: "ruby",
        S: "s",
        SCRIPT: "script",
        SEARCH: "search",
        SECTION: "section",
        SELECT: "select",
        SOURCE: "source",
        SMALL: "small",
        SPAN: "span",
        STRIKE: "strike",
        STRONG: "strong",
        STYLE: "style",
        SUB: "sub",
        SUMMARY: "summary",
        SUP: "sup",
        TABLE: "table",
        TBODY: "tbody",
        TEMPLATE: "template",
        TEXTAREA: "textarea",
        TFOOT: "tfoot",
        TD: "td",
        TH: "th",
        THEAD: "thead",
        TITLE: "title",
        TR: "tr",
        TRACK: "track",
        TT: "tt",
        U: "u",
        UL: "ul",
        SVG: "svg",
        VAR: "var",
        WBR: "wbr",
        XMP: "xmp",
    },

    TAG_ID = {
        UNKNOWN: 0, 0: "UNKNOWN",
        A: 1, 1: "A",
        ADDRESS: 2, 2: "ADDRESS",
        ANNOTATION_XML: 3, 3: "ANNOTATION_XML",
        APPLET: 4, 4: "APPLET",
        AREA: 5, 5: "AREA",
        ARTICLE: 6, 6: "ARTICLE",
        ASIDE: 7, 7: "ASIDE",
        B: 8, 8: "B",
        BASE: 9, 9: "BASE",
        BASEFONT: 10, 10: "BASEFONT",
        BGSOUND: 11, 11: "BGSOUND",
        BIG: 12, 12: "BIG",
        BLOCKQUOTE: 13, 13: "BLOCKQUOTE",
        BODY: 14, 14: "BODY",
        BR: 15, 15: "BR",
        BUTTON: 16, 16: "BUTTON",
        CAPTION: 17, 17: "CAPTION",
        CENTER: 18, 18: "CENTER",
        CODE: 19, 19: "CODE",
        COL: 20, 20: "COL",
        COLGROUP: 21, 21: "COLGROUP",
        DD: 22, 22: "DD",
        DESC: 23, 23: "DESC",
        DETAILS: 24, 24: "DETAILS",
        DIALOG: 25, 25: "DIALOG",
        DIR: 26, 26: "DIR",
        DIV: 27, 27: "DIV",
        DL: 28, 28: "DL",
        DT: 29, 29: "DT",
        EM: 30, 30: "EM",
        EMBED: 31, 31: "EMBED",
        FIELDSET: 32, 32: "FIELDSET",
        FIGCAPTION: 33, 33: "FIGCAPTION",
        FIGURE: 34, 34: "FIGURE",
        FONT: 35, 35: "FONT",
        FOOTER: 36, 36: "FOOTER",
        FOREIGN_OBJECT: 37, 37: "FOREIGN_OBJECT",
        FORM: 38, 38: "FORM",
        FRAME: 39, 39: "FRAME",
        FRAMESET: 40, 40: "FRAMESET",
        H1: 41, 41: "H1",
        H2: 42, 42: "H2",
        H3: 43, 43: "H3",
        H4: 44, 44: "H4",
        H5: 45, 45: "H5",
        H6: 46, 46: "H6",
        HEAD: 47, 47: "HEAD",
        HEADER: 48, 48: "HEADER",
        HGROUP: 49, 49: "HGROUP",
        HR: 50, 50: "HR",
        HTML: 51, 51: "HTML",
        I: 52, 52: "I",
        IMG: 53, 53: "IMG",
        IMAGE: 54, 54: "IMAGE",
        INPUT: 55, 55: "INPUT",
        IFRAME: 56, 56: "IFRAME",
        KEYGEN: 57, 57: "KEYGEN",
        LABEL: 58, 58: "LABEL",
        LI: 59, 59: "LI",
        LINK: 60, 60: "LINK",
        LISTING: 61, 61: "LISTING",
        MAIN: 62, 62: "MAIN",
        MALIGNMARK: 63, 63: "MALIGNMARK",
        MARQUEE: 64, 64: "MARQUEE",
        MATH: 65, 65: "MATH",
        MENU: 66, 66: "MENU",
        META: 67, 67: "META",
        MGLYPH: 68, 68: "MGLYPH",
        MI: 69, 69: "MI",
        MO: 70, 70: "MO",
        MN: 71, 71: "MN",
        MS: 72, 72: "MS",
        MTEXT: 73, 73: "MTEXT",
        NAV: 74, 74: "NAV",
        NOBR: 75, 75: "NOBR",
        NOFRAMES: 76, 76: "NOFRAMES",
        NOEMBED: 77, 77: "NOEMBED",
        NOSCRIPT: 78, 78: "NOSCRIPT",
        OBJECT: 79, 79: "OBJECT",
        OL: 80, 80: "OL",
        OPTGROUP: 81, 81: "OPTGROUP",
        OPTION: 82, 82: "OPTION",
        P: 83, 83: "P",
        PARAM: 84, 84: "PARAM",
        PLAINTEXT: 85, 85: "PLAINTEXT",
        PRE: 86, 86: "PRE",
        RB: 87, 87: "RB",
        RP: 88, 88: "RP",
        RT: 89, 89: "RT",
        RTC: 90, 90: "RTC",
        RUBY: 91, 91: "RUBY",
        S: 92, 92: "S",
        SCRIPT: 93, 93: "SCRIPT",
        SEARCH: 94, 94: "SEARCH",
        SECTION: 95, 95: "SECTION",
        SELECT: 96, 96: "SELECT",
        SOURCE: 97, 97: "SOURCE",
        SMALL: 98, 98: "SMALL",
        SPAN: 99, 99: "SPAN",
        STRIKE: 100, 100: "STRIKE",
        STRONG: 101, 101: "STRONG",
        STYLE: 102, 102: "STYLE",
        SUB: 103, 103: "SUB",
        SUMMARY: 104, 104: "SUMMARY",
        SUP: 105, 105: "SUP",
        TABLE: 106, 106: "TABLE",
        TBODY: 107, 107: "TBODY",
        TEMPLATE: 108, 108: "TEMPLATE",
        TEXTAREA: 109, 109: "TEXTAREA",
        TFOOT: 110, 110: "TFOOT",
        TD: 111, 111: "TD",
        TH: 112, 112: "TH",
        THEAD: 113, 113: "THEAD",
        TITLE: 114, 114: "TITLE",
        TR: 115, 115: "TR",
        TRACK: 116, 116: "TRACK",
        TT: 117, 117: "TT",
        U: 118, 118: "U",
        UL: 119, 119: "UL",
        SVG: 120, 120: "SVG",
        VAR: 121, 121: "VAR",
        WBR: 122, 122: "WBR",
        XMP: 123, 123: "XMP"
    },

    TAG_NAME_TO_ID = new Map([
        [TAG_NAMES.A, TAG_ID.A],
        [TAG_NAMES.ADDRESS, TAG_ID.ADDRESS],
        [TAG_NAMES.ANNOTATION_XML, TAG_ID.ANNOTATION_XML],
        [TAG_NAMES.APPLET, TAG_ID.APPLET],
        [TAG_NAMES.AREA, TAG_ID.AREA],
        [TAG_NAMES.ARTICLE, TAG_ID.ARTICLE],
        [TAG_NAMES.ASIDE, TAG_ID.ASIDE],
        [TAG_NAMES.B, TAG_ID.B],
        [TAG_NAMES.BASE, TAG_ID.BASE],
        [TAG_NAMES.BASEFONT, TAG_ID.BASEFONT],
        [TAG_NAMES.BGSOUND, TAG_ID.BGSOUND],
        [TAG_NAMES.BIG, TAG_ID.BIG],
        [TAG_NAMES.BLOCKQUOTE, TAG_ID.BLOCKQUOTE],
        [TAG_NAMES.BODY, TAG_ID.BODY],
        [TAG_NAMES.BR, TAG_ID.BR],
        [TAG_NAMES.BUTTON, TAG_ID.BUTTON],
        [TAG_NAMES.CAPTION, TAG_ID.CAPTION],
        [TAG_NAMES.CENTER, TAG_ID.CENTER],
        [TAG_NAMES.CODE, TAG_ID.CODE],
        [TAG_NAMES.COL, TAG_ID.COL],
        [TAG_NAMES.COLGROUP, TAG_ID.COLGROUP],
        [TAG_NAMES.DD, TAG_ID.DD],
        [TAG_NAMES.DESC, TAG_ID.DESC],
        [TAG_NAMES.DETAILS, TAG_ID.DETAILS],
        [TAG_NAMES.DIALOG, TAG_ID.DIALOG],
        [TAG_NAMES.DIR, TAG_ID.DIR],
        [TAG_NAMES.DIV, TAG_ID.DIV],
        [TAG_NAMES.DL, TAG_ID.DL],
        [TAG_NAMES.DT, TAG_ID.DT],
        [TAG_NAMES.EM, TAG_ID.EM],
        [TAG_NAMES.EMBED, TAG_ID.EMBED],
        [TAG_NAMES.FIELDSET, TAG_ID.FIELDSET],
        [TAG_NAMES.FIGCAPTION, TAG_ID.FIGCAPTION],
        [TAG_NAMES.FIGURE, TAG_ID.FIGURE],
        [TAG_NAMES.FONT, TAG_ID.FONT],
        [TAG_NAMES.FOOTER, TAG_ID.FOOTER],
        [TAG_NAMES.FOREIGN_OBJECT, TAG_ID.FOREIGN_OBJECT],
        [TAG_NAMES.FORM, TAG_ID.FORM],
        [TAG_NAMES.FRAME, TAG_ID.FRAME],
        [TAG_NAMES.FRAMESET, TAG_ID.FRAMESET],
        [TAG_NAMES.H1, TAG_ID.H1],
        [TAG_NAMES.H2, TAG_ID.H2],
        [TAG_NAMES.H3, TAG_ID.H3],
        [TAG_NAMES.H4, TAG_ID.H4],
        [TAG_NAMES.H5, TAG_ID.H5],
        [TAG_NAMES.H6, TAG_ID.H6],
        [TAG_NAMES.HEAD, TAG_ID.HEAD],
        [TAG_NAMES.HEADER, TAG_ID.HEADER],
        [TAG_NAMES.HGROUP, TAG_ID.HGROUP],
        [TAG_NAMES.HR, TAG_ID.HR],
        [TAG_NAMES.HTML, TAG_ID.HTML],
        [TAG_NAMES.I, TAG_ID.I],
        [TAG_NAMES.IMG, TAG_ID.IMG],
        [TAG_NAMES.IMAGE, TAG_ID.IMAGE],
        [TAG_NAMES.INPUT, TAG_ID.INPUT],
        [TAG_NAMES.IFRAME, TAG_ID.IFRAME],
        [TAG_NAMES.KEYGEN, TAG_ID.KEYGEN],
        [TAG_NAMES.LABEL, TAG_ID.LABEL],
        [TAG_NAMES.LI, TAG_ID.LI],
        [TAG_NAMES.LINK, TAG_ID.LINK],
        [TAG_NAMES.LISTING, TAG_ID.LISTING],
        [TAG_NAMES.MAIN, TAG_ID.MAIN],
        [TAG_NAMES.MALIGNMARK, TAG_ID.MALIGNMARK],
        [TAG_NAMES.MARQUEE, TAG_ID.MARQUEE],
        [TAG_NAMES.MATH, TAG_ID.MATH],
        [TAG_NAMES.MENU, TAG_ID.MENU],
        [TAG_NAMES.META, TAG_ID.META],
        [TAG_NAMES.MGLYPH, TAG_ID.MGLYPH],
        [TAG_NAMES.MI, TAG_ID.MI],
        [TAG_NAMES.MO, TAG_ID.MO],
        [TAG_NAMES.MN, TAG_ID.MN],
        [TAG_NAMES.MS, TAG_ID.MS],
        [TAG_NAMES.MTEXT, TAG_ID.MTEXT],
        [TAG_NAMES.NAV, TAG_ID.NAV],
        [TAG_NAMES.NOBR, TAG_ID.NOBR],
        [TAG_NAMES.NOFRAMES, TAG_ID.NOFRAMES],
        [TAG_NAMES.NOEMBED, TAG_ID.NOEMBED],
        [TAG_NAMES.NOSCRIPT, TAG_ID.NOSCRIPT],
        [TAG_NAMES.OBJECT, TAG_ID.OBJECT],
        [TAG_NAMES.OL, TAG_ID.OL],
        [TAG_NAMES.OPTGROUP, TAG_ID.OPTGROUP],
        [TAG_NAMES.OPTION, TAG_ID.OPTION],
        [TAG_NAMES.P, TAG_ID.P],
        [TAG_NAMES.PARAM, TAG_ID.PARAM],
        [TAG_NAMES.PLAINTEXT, TAG_ID.PLAINTEXT],
        [TAG_NAMES.PRE, TAG_ID.PRE],
        [TAG_NAMES.RB, TAG_ID.RB],
        [TAG_NAMES.RP, TAG_ID.RP],
        [TAG_NAMES.RT, TAG_ID.RT],
        [TAG_NAMES.RTC, TAG_ID.RTC],
        [TAG_NAMES.RUBY, TAG_ID.RUBY],
        [TAG_NAMES.S, TAG_ID.S],
        [TAG_NAMES.SCRIPT, TAG_ID.SCRIPT],
        [TAG_NAMES.SEARCH, TAG_ID.SEARCH],
        [TAG_NAMES.SECTION, TAG_ID.SECTION],
        [TAG_NAMES.SELECT, TAG_ID.SELECT],
        [TAG_NAMES.SOURCE, TAG_ID.SOURCE],
        [TAG_NAMES.SMALL, TAG_ID.SMALL],
        [TAG_NAMES.SPAN, TAG_ID.SPAN],
        [TAG_NAMES.STRIKE, TAG_ID.STRIKE],
        [TAG_NAMES.STRONG, TAG_ID.STRONG],
        [TAG_NAMES.STYLE, TAG_ID.STYLE],
        [TAG_NAMES.SUB, TAG_ID.SUB],
        [TAG_NAMES.SUMMARY, TAG_ID.SUMMARY],
        [TAG_NAMES.SUP, TAG_ID.SUP],
        [TAG_NAMES.TABLE, TAG_ID.TABLE],
        [TAG_NAMES.TBODY, TAG_ID.TBODY],
        [TAG_NAMES.TEMPLATE, TAG_ID.TEMPLATE],
        [TAG_NAMES.TEXTAREA, TAG_ID.TEXTAREA],
        [TAG_NAMES.TFOOT, TAG_ID.TFOOT],
        [TAG_NAMES.TD, TAG_ID.TD],
        [TAG_NAMES.TH, TAG_ID.TH],
        [TAG_NAMES.THEAD, TAG_ID.THEAD],
        [TAG_NAMES.TITLE, TAG_ID.TITLE],
        [TAG_NAMES.TR, TAG_ID.TR],
        [TAG_NAMES.TRACK, TAG_ID.TRACK],
        [TAG_NAMES.TT, TAG_ID.TT],
        [TAG_NAMES.U, TAG_ID.U],
        [TAG_NAMES.UL, TAG_ID.UL],
        [TAG_NAMES.SVG, TAG_ID.SVG],
        [TAG_NAMES.VAR, TAG_ID.VAR],
        [TAG_NAMES.WBR, TAG_ID.WBR],
        [TAG_NAMES.XMP, TAG_ID.XMP],
    ]),

    getTagID = (tagName) => {
        return TAG_NAME_TO_ID.get(tagName) ?? TAG_ID.UNKNOWN;
    },

    SPECIAL_ELEMENTS = {
        [NS.HTML]: new Set([
            TAG_ID.ADDRESS,
            TAG_ID.APPLET,
            TAG_ID.AREA,
            TAG_ID.ARTICLE,
            TAG_ID.ASIDE,
            TAG_ID.BASE,
            TAG_ID.BASEFONT,
            TAG_ID.BGSOUND,
            TAG_ID.BLOCKQUOTE,
            TAG_ID.BODY,
            TAG_ID.BR,
            TAG_ID.BUTTON,
            TAG_ID.CAPTION,
            TAG_ID.CENTER,
            TAG_ID.COL,
            TAG_ID.COLGROUP,
            TAG_ID.DD,
            TAG_ID.DETAILS,
            TAG_ID.DIR,
            TAG_ID.DIV,
            TAG_ID.DL,
            TAG_ID.DT,
            TAG_ID.EMBED,
            TAG_ID.FIELDSET,
            TAG_ID.FIGCAPTION,
            TAG_ID.FIGURE,
            TAG_ID.FOOTER,
            TAG_ID.FORM,
            TAG_ID.FRAME,
            TAG_ID.FRAMESET,
            TAG_ID.H1,
            TAG_ID.H2,
            TAG_ID.H3,
            TAG_ID.H4,
            TAG_ID.H5,
            TAG_ID.H6,
            TAG_ID.HEAD,
            TAG_ID.HEADER,
            TAG_ID.HGROUP,
            TAG_ID.HR,
            TAG_ID.HTML,
            TAG_ID.IFRAME,
            TAG_ID.IMG,
            TAG_ID.INPUT,
            TAG_ID.LI,
            TAG_ID.LINK,
            TAG_ID.LISTING,
            TAG_ID.MAIN,
            TAG_ID.MARQUEE,
            TAG_ID.MENU,
            TAG_ID.META,
            TAG_ID.NAV,
            TAG_ID.NOEMBED,
            TAG_ID.NOFRAMES,
            TAG_ID.NOSCRIPT,
            TAG_ID.OBJECT,
            TAG_ID.OL,
            TAG_ID.P,
            TAG_ID.PARAM,
            TAG_ID.PLAINTEXT,
            TAG_ID.PRE,
            TAG_ID.SCRIPT,
            TAG_ID.SECTION,
            TAG_ID.SELECT,
            TAG_ID.SOURCE,
            TAG_ID.STYLE,
            TAG_ID.SUMMARY,
            TAG_ID.TABLE,
            TAG_ID.TBODY,
            TAG_ID.TD,
            TAG_ID.TEMPLATE,
            TAG_ID.TEXTAREA,
            TAG_ID.TFOOT,
            TAG_ID.TH,
            TAG_ID.THEAD,
            TAG_ID.TITLE,
            TAG_ID.TR,
            TAG_ID.TRACK,
            TAG_ID.UL,
            TAG_ID.WBR,
            TAG_ID.XMP,
        ]),
        [NS.MATHML]: new Set([TAG_ID.MI, TAG_ID.MO, TAG_ID.MN, TAG_ID.MS, TAG_ID.MTEXT, TAG_ID.ANNOTATION_XML]),
        [NS.SVG]: new Set([TAG_ID.TITLE, TAG_ID.FOREIGN_OBJECT, TAG_ID.DESC]),
        [NS.XLINK]: new Set(),
        [NS.XML]: new Set(),
        [NS.XMLNS]: new Set(),
    }

    NUMBERED_HEADERS = new Set([TAG_ID.H1, TAG_ID.H2, TAG_ID.H3, TAG_ID.H4, TAG_ID.H5, TAG_ID.H6]),

    UNESCAPED_TEXT = new Set([
        TAG_NAMES.STYLE,
        TAG_NAMES.SCRIPT,
        TAG_NAMES.XMP,
        TAG_NAMES.IFRAME,
        TAG_NAMES.NOEMBED,
        TAG_NAMES.NOFRAMES,
        TAG_NAMES.PLAINTEXT,
    ]),

    hasUnescapedText = (tn, scriptingEnabled) => {
        return UNESCAPED_TEXT.has(tn) || (scriptingEnabled && tn === TAG_NAMES.NOSCRIPT),
    }
;
